name:
  wesley

logging:
  level:
    org.springframework.boot: debug

context:
  # 通过配置添加的 应用监听器, 会被 默认加载的DelegatingApplicationListener 发现
  listener:
    classes: com.wesley.springboot.listener.ThirdListener
  # 通过配置添加的 应用上下文初始化器 原理是 会被 DelegatingApplicationContextInitializer 发现
  initializer:
    classes: com.wesley.springboot.initializer.ThirdInitializer

wesley:
  starter:
    enabled: true
  academy:
    addr: athens_addr_15